#!/usr/bin/env python3
"""
Convert AzerothCore .conf keys into the AC_* environment variables the server reads.

This is a faithful port of IniKeyToEnvVarKey() from
src/common/Configuration/Config.cpp in the mod-playerbots AzerothCore fork.

Do NOT hand-write AC_* variable names. The conversion is not "uppercase and
replace dots" -- it also splits camelCase and letter/digit boundaries, so
    Death.CorpseReclaimDelay.PvE  ->  AC_DEATH_CORPSE_RECLAIM_DELAY_PV_E
which nobody guesses correctly. Always generate them with this script.

Usage:
    ./ini2env.py family-settings.ini > family.env     # convert a whole file
    ./ini2env.py --key Rate.XP.Kill                   # convert one key
    ./ini2env.py --selftest                           # verify the algorithm
"""

import argparse
import sys


def ini_key_to_env_key(key: str) -> str:
    """Port of AzerothCore's IniKeyToEnvVarKey()."""
    result = []
    n = len(key)

    for i, curr in enumerate(key):
        if curr in (" ", ".", "-"):
            result.append("_")
            continue

        is_end = i == n - 1
        if not is_end:
            nxt = key[i + 1]

            # "aB" -> "A_B"
            if not curr.isupper() and nxt.isupper():
                result.append(curr.upper())
                result.append("_")
                continue

            curr_num = curr.isdigit()
            next_num = nxt.isdigit()

            # "a1" -> "A_1"  and  "1a" -> "1_A"
            if curr_num != next_num:
                result.append(curr.upper())
                result.append("_")
                continue

        result.append(curr.upper())

    return "".join(result)


def env_var_name(config_name: str) -> str:
    return "AC_" + ini_key_to_env_key(config_name)


SELFTESTS = [
    # (ini key, expected env var) -- first three are from the AzerothCore source comments
    ("SomeConfig", "AC_SOME_CONFIG"),
    ("myNestedConfig.opt1", "AC_MY_NESTED_CONFIG_OPT_1"),
    ("LogDB.Opt.ClearTime", "AC_LOG_DB_OPT_CLEAR_TIME"),
    # this one is from the mod-playerbots wiki
    ("AiPlayerbot.MinRandomBots", "AC_AI_PLAYERBOT_MIN_RANDOM_BOTS"),
    # keys we actually rely on
    ("Rate.XP.Kill", "AC_RATE_XP_KILL"),
    ("GameType", "AC_GAME_TYPE"),
    ("MapUpdate.Threads", "AC_MAP_UPDATE_THREADS"),
    ("DurabilityLoss.OnDeath", "AC_DURABILITY_LOSS_ON_DEATH"),
    ("Death.CorpseReclaimDelay.PvE", "AC_DEATH_CORPSE_RECLAIM_DELAY_PV_E"),
    # the new modules -- digit boundaries are exactly why this script exists
    ("AutoBalance.Enable.5M", "AC_AUTO_BALANCE_ENABLE_5_M"),
    ("AutoBalance.InflectionPointRaid10M.CurveFloor",
     "AC_AUTO_BALANCE_INFLECTION_POINT_RAID_10_M_CURVE_FLOOR"),
    ("AutoBalance.playerCountDifficultyOffset",
     "AC_AUTO_BALANCE_PLAYER_COUNT_DIFFICULTY_OFFSET"),
    ("Transmogrification.AllowMixedArmorTypes",
     "AC_TRANSMOGRIFICATION_ALLOW_MIXED_ARMOR_TYPES"),
]


def selftest() -> int:
    failed = 0
    for key, expected in SELFTESTS:
        got = env_var_name(key)
        ok = got == expected
        failed += 0 if ok else 1
        print(f"{'ok  ' if ok else 'FAIL'}  {key:<34} -> {got}"
              + ("" if ok else f"   (expected {expected})"))
    print(f"\n{len(SELFTESTS) - failed}/{len(SELFTESTS)} passed")
    return 1 if failed else 0


def convert_file(path: str) -> int:
    print("# Generated by scripts/ini2env.py -- do not edit by hand.")
    print(f"# Source: {path}")
    for raw in open(path, encoding="utf-8"):
        line = raw.strip()
        if not line:
            print()
            continue
        if line.startswith("#"):
            print(line)
            continue
        if "=" not in line:
            print(f"# ?? skipped unparseable line: {line}", file=sys.stderr)
            continue
        key, value = line.split("=", 1)
        key, value = key.strip(), value.strip()
        if not key:
            continue
        print(f"{env_var_name(key)}={value}")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("file", nargs="?", help="INI-style file of AzerothCore config keys")
    p.add_argument("--key", help="convert a single config key and exit")
    p.add_argument("--selftest", action="store_true", help="verify the conversion algorithm")
    args = p.parse_args()

    if args.selftest:
        return selftest()
    if args.key:
        print(env_var_name(args.key))
        return 0
    if args.file:
        return convert_file(args.file)

    p.print_help()
    return 1


if __name__ == "__main__":
    sys.exit(main())
